Module 5
js-tasks-ru/jsbasic-20221028_borisnovikov4815 pull request #3
Opened 2022-12-04 14:14 UTC by BorisNovi

2022-12-04 14:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-05 04:39 UTC, koalex requested changes
Исправить **5-2**

2022-12-05 04:39 UTC, koalex commented on 5-module/2-task/index.js
> +  document.addEventListener('click', function(event){
Здесь надо на кнопку навешивать листенер, вот так должно быть:
```
function toggleText() {
   let toggleButton = document.querySelector('.toggle-text-button');
   let textElement = document.getElementById('text');

   toggleButton.addEventListener('click', () => {
     let isTextElementHidden = textElement.hidden;
     textElement.hidden = !isTextElementHidden;
   });
 }
```

2022-12-06 15:36 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-06 15:36 UTC, BorisNovi commented on 5-module/2-task/index.js
> +  document.addEventListener('click', function(event){
Исправил

2022-12-06 15:57 UTC, koalex approved these changes

2022-12-06 15:58 UTC, merged