third done
js-tasks-ru/jsbasic-20221028_borisnovikov4815 pull request #4
Opened 2022-12-16 14:53 UTC by BorisNovi

2022-12-16 14:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-20 05:01 UTC, koalex requested changes
**6-2** надо исправить
[решение](https://github.com/js-tasks-ru/jsbasic-20221028_konstantin-alexandrov/blob/69c56e523cc63f0ae8a8654253697bffc01b7dfb/6-module/2-task/index.js)

2023-01-01 12:09 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-01 13:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-01-01 15:26 UTC, koalex approved these changes

2023-01-01 15:27 UTC, merged