ok
js-tasks-ru/jsbasic-20221028_borisnovikov4815 pull request #6
Opened 2023-01-14 20:01 UTC by BorisNovi

2023-01-14 20:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-20 03:39 UTC, koalex requested changes
Исправить последствия конфликта в **8-2**

2023-02-20 03:39 UTC, koalex commented on 8-module/2-task/index.js
> +<<<<<<< HEAD
Удалить **стр 9**

2023-02-20 03:39 UTC, koalex commented on 8-module/2-task/index.js
> +=======
Удалить `стр 36-38`

2023-02-21 22:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-02-22 09:39 UTC, koalex approved these changes

2023-02-22 09:40 UTC, merged